---
title: "heatmaps"
author: "Franziska Hildebrandt"
date: "1/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Generation of heatmaps for sc-TG-DC data to visualize DGE in different classes and clusters.

Generate an annotation table including GO terms and names using bioMart and the original count data. Subsequently subset it to only receive genes in the table that are also present in your DEG table and append it to the DEG table.


```{r, create table with Gene ontologies of interest}

mart <- useMart("ensembl", dataset = "mmusculus_gene_ensembl")

go.table <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id", "external_gene_name", "description", "go_id","name_1006", "namespace_1003"), values= rownames(dc.data.mus), mart= mart)

#write.table(genes.table,file="data/ILC/gene_name_go_translation.tab",sep="\t")

```

```{r, subset DGEA according to immune related processes - 12h - cluster 5 markers in comparison to cluster 2}

go.12h <- go.table[go.table$external_gene_name %in% rownames(dc.12h.markers) ,]

#subset so you only have the "immune system process" genes 

go.12h.im <- go.12h[go.12h$name_1006 == "immune system process" ,]

#subset the DEG at 12h for only genes related to immune system processes

DEG_12h_im <- m12hLDM[rownames(m12hLDM) %in% go.12h.im$external_gene_name ,]

```

```{r, subset DGEA according to immune related processes}

#Input: pairwise DE for mature vs. immature cells at 12h 

go.12h <- go.table[go.table$external_gene_name %in% rownames(dc.12h.markers) ,]

#subset so you only have the "immune system process" genes 

go.12h.im <- go.12h[go.12h$name_1006 == "immune system process" ,]

#subset the DEG at 12h for only genes related to immune system processes

DEG_12h_im_ldm <- dc.12h.markers[rownames(dc.12h.markers) %in% go.12h.im$external_gene_name ,]

```

```{r, subset DGEA according to the top GO term of cluster 4 and 5 - repsonse to stress}

#Input: pairwise DE for mature vs. immature cells at 12h 

go.12h <- go.table[go.table$external_gene_name %in% rownames(dc.12h.markers) ,]

#Paste the name together with the GO_term

go.12h$gene_GO <- paste0(go.12h$external_gene_name, "::",go.12h$name_1006)
go.12h$gene_description <- paste0(go.12h$external_gene_name, "::", go.12h$description)

#subset so you only have the "immune system process" genes 

go.12h.im <- go.12h[go.12h$name_1006 == "immune system process" ,]

#subset the DEG at 12h for only genes related to immune system processes

DEG_12h_im_ldm <- dc.12h.markers[rownames(dc.12h.markers) %in% go.12h.im$external_gene_name ,]

```


```{r, subset pairwise DGEA according to immune related processes - 3h}

go.3h <- go.table[go.table$external_gene_name %in% rownames(DEG_maturation_infection3h) ,]

#subset so you only have the "immune system process" genes 

go.3h.im <- go.3h[go.3h$name_1006 == "immune system process" ,]

#subset the DEG at 12h for only genes related to immune system processes

DEG_maturation_3h_im <- DEG_maturation_infection3h[rownames(DEG_maturation_infection3h) %in% go.3h.im$external_gene_name ,]

```


```{r, define gene sets for comparison}


#mature (GM-DC)


#immature (GM-Macs)


#classical activation
c.clas <- c("Ccr7", "Ccl5", "Cxcl11", "Oasl2", "Irf7", "Traf1", "Il15ra", "Relb", "Tlr2", "Cxcl16", "Stat1", "Nfkbie", "Il23a", "Ccl3")

#alternative activation
c.alt <- c("Arg1", "Chil3", "Mgl2", "Ccl24", "Mrc1", "Pdcd1lg2", "Ptgs1", "Igf1", "Irf4", "Clec7a", "Retnla", "Ccl17")




```

```{r generate matrix to plot heatmaps}

gene_data <- data.frame(t(as.matrix(se.dc.mus@assays$RNA@data)),cluster=se.dc.mus$cell_class,check.names = F)
average_data <- aggregate(.~cluster, gene_data, mean)
cluster_name <- average_data[,1]
average_data <- apply(average_data[,2:ncol(average_data)],2,as.numeric)
rownames(average_data) <- cluster_name
average_data <- t(average_data)
phmat1 <- t(scale(t(average_data)))
phmat1[phmat1> 1.5] <- 1.5
phmat1[phmat1 < -1.5] <- -1.5

gene_data <- data.frame(t(as.matrix(se.12h@assays$RNA@data)),cluster=se.12h$seurat_clusters,check.names = F)
average_data <- aggregate(.~cluster, gene_data, mean)
cluster_name <- average_data[,1]
average_data <- apply(average_data[,2:ncol(average_data)],2,as.numeric)
rownames(average_data) <- cluster_name
average_data <- t(average_data)
phmat2 <- t(scale(t(average_data)))
phmat2[phmat2> 1.5] <- 1.5
phmat2[phmat2 < -1.5] <- -1.5

gene_data <- data.frame(t(as.matrix(se.12h@assays$RNA@data)),cluster=se.12h$cluster_maturation,check.names = F)
average_data <- aggregate(.~cluster, gene_data, mean)
cluster_name <- average_data[,1]
average_data <- apply(average_data[,2:ncol(average_data)],2,as.numeric)
rownames(average_data) <- cluster_name
average_data <- t(average_data)
phmat3 <- t(scale(t(average_data)))
phmat3[phmat3> 1.5] <- 1.5
phmat3[phmat3 < -1.5] <- -1.5

gene_data <- data.frame(t(as.matrix(se.12h@assays$RNA@data)),cluster=se.12h$cell_class_maturation,check.names = F)
average_data <- aggregate(.~cluster, gene_data, mean)
cluster_name <- average_data[,1]
average_data <- apply(average_data[,2:ncol(average_data)],2,as.numeric)
rownames(average_data) <- cluster_name
average_data <- t(average_data)
phmat4 <- t(scale(t(average_data)))
phmat4[phmat4> 1.5] <- 1.5
phmat4[phmat4 < -1.5] <- -1.5

gene_data <- data.frame(t(as.matrix(se.12h@assays$RNA@data)),cluster=se.12h$cluster_and_cell_class,check.names = F)
average_data <- aggregate(.~cluster, gene_data, mean)
cluster_name <- average_data[,1]
average_data <- apply(average_data[,2:ncol(average_data)],2,as.numeric)
rownames(average_data) <- cluster_name
average_data <- t(average_data)
phmat5 <- t(scale(t(average_data)))
phmat5[phmat5> 1.5] <- 1.5
phmat5[phmat5 < -1.5] <- -1.5


```

```{r, subset matrices accordingto to the groups of interest}

#subset bu columns
phmat12 <- phmat1[,c(1:4,9:12)]
phmat3 <- phmat1[, c(5:8,13:16)]

```

```{r, plot heatmaps, width = 10, height = 20}

alt.hmap <- pheatmap(phmat1[c.alt,], fontsize_row = 8, cellwidth = 15, clustering_distance_rows = "correlation", cluster_cols = F, color = colorRampPalette(c("#440154" ,"#21908C", "#FDE725"))(200))

clas.hmap <- pheatmap(phmat1[c.clas,], fontsize_row = 8, cellwidth = 15, clustering_distance_rows = "correlation", cluster_cols = F, color = colorRampPalette(c("#440154" ,"#21908C", "#FDE725"))(200))

png("~/Desktop/heatmap_12h_clusters_immune_processes.png", height = 16, width = 8, units = "cm", res = 600)
print(mat_12h_LDM_up <- pheatmap(phmat1[rownames(DEG_12h_im_ldm),], fontsize_row = 8, cellwidth = 15, clustering_distance_rows = "correlation", cluster_cols = F,color = colorRampPalette(c("#440154" ,"#21908C", "#FDE725"))(1000)))
dev.off()

mat_12h_PTG_up <- pheatmap(phmat1[rownames(DEG_12h_im_ptg),], fontsize_row = 8, cellwidth = 15, clustering_distance_rows = "correlation", cluster_cols = F, color = colorRampPalette(c("#440154" ,"#21908C", "#FDE725"))(1000))

mat_12h <- pheatmap(phmat2[rownames(DEG_12h_im),], fontsize_row = 8, cellwidth = 15, clustering_distance_rows = "correlation", cluster_cols = F, color = colorRampPalette(c("#440154" ,"#21908C", "#FDE725"))(1000))

mat_12h <- pheatmap(phmat3[rownames(DEG_12h_im),], fontsize_row = 8, cellwidth = 15, clustering_distance_rows = "correlation", cluster_cols = F, color = colorRampPalette(c("#440154" ,"#21908C", "#FDE725"))(1000))

png("~/t.gondi_dc/res/heatmap_class_mat_all_markers.png", res = 300, units = "cm", height = 20, width = 7)
print(mat_12h <- pheatmap(phmat4[rownames(dc.12h.markers),], fontsize_row = 5, cellwidth = 15, clustering_distance_rows = "correlation", cluster_cols = F, color = colorRampPalette(c("#440154" ,"#21908C", "#FDE725"))(1000)))
dev.off()


mat_12h <- pheatmap(phmat5[rownames(DEG_12h_im),], fontsize_row = 8, cellwidth = 15, clustering_distance_rows = "correlation", cluster_cols = F, color = colorRampPalette(c("#440154" ,"#21908C", "#FDE725"))(1000))


```


```{r}

gene_data <- data.frame(t(as.matrix(toxo@assays$RNA@data)),cluster=toxo$group,check.names = F)
average_data <- aggregate(.~cluster, gene_data, mean)
cluster_name <- average_data[,1]
average_data <- apply(average_data[,2:ncol(average_data)],2,as.numeric)
rownames(average_data) <- cluster_name
average_data <- t(average_data)
phmat1 <- t(scale(t(average_data)))
phmat1[phmat1> 1.5] <- 1.5
phmat1[phmat1 < -1.5] <- -1.5

```


```{r}

as.data.frame(phmat1)
phmat1 <- as.data.frame(phmat1)
m <- as.data.frame(m, col.names = "gene")
names(m)[1]<- paste("gene")
phmat1 <- subset(phmat1, gene %in% m$gene)
phmat1 <- as.matrix(phmat1)

```

