---
title: "GEO analysis - MicroArray - GM-DC_GM-Mac"
output: html_notebook
---

```{r, load libraries}

library(SpikeInSubset)
library(genefilter)
library(limma)
library(oligo)
library(affy)

```


```{r, import data}


#create sample-info sheet for the datasets containing samplenames 
#GSE62361
geo_dir <- "~/t.gondi_dc/data/GEO_comparions/GSE62361_RAW/"
lgeo_1 <- list.files(geo_dir, full.names = T)
dat1 <- read.celfiles(lgeo_1)
#GSE62746
geo_dir_2 <- "~/t.gondi_dc/data/GEO_comparions/GSE62746_RAW/"
lgeo_2 <- list.files(geo_dir_2, full.names = T)
dat2 <- read.celfiles(lgeo_2)

```

```{r, analyse data}

#define phenodata 
ph <- dat1@phenoData
ph$index
ph@data

#index 1-3: DC
#index 4-6: MAC

```

```{r, normalize data}

data.rma = rma(dat1)
data.matrix = exprs(data.rma)

```


```{r, limma for DGEA}

#Define groups to compare

ph@data[,2] = c("DC", "DC", "DC", "MAC", "MAC", "MAC")
colnames(ph@data)[2] = "source"
ph@data

#define the groups
groups = ph@data$source

#transform into factors

f = factor(groups,levels=c("DC","MAC"))

#make design model

design = model.matrix(~ 0 + f)
colnames(design) = c("DC","MAC")

data.fit = lmFit(data.matrix,design)

data.fit$coefficients[1:10,]

#tell limma which groups to compare:
contrast.matrix = makeContrasts(DC-MAC,levels=design)
data.fit.con = contrasts.fit(data.fit,contrast.matrix)

#perform two groups using a t-test 
data.fit.eb = eBayes(data.fit.con)
names(data.fit.eb)

#log fold changes are in the coefficents slot

data.fit.eb$coefficients[1:10,]

#adjust the p-value
options(digits=2)

deg1 = topTable(data.fit.eb,coef=1,number=200,adjust.method= "BH")


```

```{r, translate probe IDs to gene symbols}

ann <- read.delim("~/t.gondi_dc/data/GEO_comparions/EnsFiltered.GPL6246.2020_09_23.2020_09_23.2020_09_16.Mmusculus.txt", header = F)
colnames(ann) <- c("ID", "human_ensmbl", "mouse_ensembl", "gene_symbol")
ann$ID <- as.character(ann$ID)
#translate 

#merge ensembl name and gene ID
deg1 <- subset(deg1, rownames(deg1) %in% intersect(rownames(deg1), ann$ID))
deg1$ID <- rownames(deg1)
deg1 <- dplyr::left_join(deg1, ann, by = "ID")
#set merged new name as rownames for gene entries

rownames(deg1) <- make.unique(deg1$gene_symbol)
deg1

deg1 <- subset(deg1, deg1$adj.P.Val < 0.05)

DCtop <- deg1[deg1[,"logFC",] > 1, ] 
MACtop <-  deg1[deg1[,"logFC",] < -1, ] 

write.table(DCtop, "~/t.gondi_dc/data/GEO_comparions/Top_DEG_DC_GSE62361.tsv", sep = "\t", quote = F, row.names = rownames(DCtop))

write.table(MACtop, "~/t.gondi_dc/data/GEO_comparions/Top_DEG_MAC_GSE62361.tsv", sep = "\t", quote = F, row.names = rownames(MACtop))

```


Now I can run the same analysis using a paired differential gene expression with the second data set which we saved as dat2. 

The first steps are similar only that we add LPS and control to the phenodata

```{r, add phenodata}

#define phenodata 
ph <- dat2@phenoData
ph$index
ph@data

#index 1-3: DC
#index 4-6: MAC

```


```{r, normalize data 2}

data.rma = rma(dat2)
data.matrix = exprs(data.rma)

```

Group variables (infection and cellype)
```{r, limma for DGEA of dat2}

#Define groups to compare

ph@data[,2] = c("DC_control", "DC_control", "DC_control", "MAC_control", "MAC_control", "MAC_control","DC_LPS", "DC_LPS", "DC_LPS", "MAC_LPS", "MAC_LPS", "MAC_LPS")

colnames(ph@data)[2]="Condition"
groups = ph@data$Condition
f = factor(groups,levels=c("DC_control","MAC_control","DC_LPS","MAC_LPS"))
design = model.matrix(~ 0 + f)
colnames(design) = levels(f)
data.fit = lmFit(data.rma, design)

#This calculates the mean log expression in each group. The contrasts of interest can be extracted by creating a contrast matrix:
#here we only want to contrast LPS infected MAC and LPS cells 
cont.matrix = makeContrasts(DCLPSvsMACLPS = DC_LPS-MAC_LPS, levels=design)
data.contr = contrasts.fit(data.fit,cont.matrix)
data.fit.eb = eBayes(data.contr)

#adjust the p-value
options(digits=2)

deg2 = topTable(data.fit.eb,coef=1,number=200,adjust.method= "BH")

deg2

##Translate 

#merge ensembl name and gene ID
deg2 <- subset(deg2, rownames(deg2) %in% intersect(rownames(deg2), ann$ID))
deg2$ID <- rownames(deg2)
deg2 <- dplyr::left_join(deg2, ann, by = "ID")
#set merged new name as rownames for gene entries

rownames(deg2) <- make.unique(deg2$gene_symbol)
deg2

deg2 <- subset(deg2, deg2$adj.P.Val < 0.05)

DC_LPS_top <- deg2[deg2[,"logFC",] > 1, ] 
MAC_LPS_top <-  deg2[deg2[,"logFC",] < -1, ] 

write.table(DC_LPS_top, "~/t.gondi_dc/data/GEO_comparions/Top_DEG_DC_LPS_GSE62746.tsv", sep = "\t", quote = F, row.names = rownames(DC_LPS_top))

write.table(MAC_LPS_top, "~/t.gondi_dc/data/GEO_comparions/Top_DEG_MAC_LPS_GSE62746.tsv", sep = "\t", quote = F, row.names = rownames(MAC_LPS_top))


```

```{r, compare four groups defined by two grouping variables using an interaction term}

ph@data[,2] = c("DC", "DC", "DC", "MAC", "MAC", "MAC","DC", "DC", "DC", "MAC", "MAC", "MAC")
x <- c("control", "LPS")
ph@data[,3] = rep(paste(x), each = 6)
colnames(ph@data)[2] = "source"
colnames(ph@data)[3] = "condition"
ph@data

#define the groups
groupsS = ph@data$source
groupsC = ph@data$condition
#transform into factors

fs <- factor(groupsS,levels=c("DC","MAC"))
fc <- factor(groupsC,levels= x)

#make paired design model

factored.design = model.matrix(~ fs*fc)
factored.design

data.fit = lmFit(data.matrix,factored.design)

data.fit$coefficients[1:10,]

#perform two groups using a t-test 
data.fit.eb = eBayes(data.fit)
names(data.fit.eb)

#log fold changes are in the coefficients slot

data.fit.eb$coefficients[1:10,]

#multiple testing for multiple comparisons
DEresults = decideTests(data.fit.eb,method='global',adjust.method="BH",p.value=0.05,lfc=1)
tail(DEresults)

sig <- subset(DEresults@.Data, DEresults@.Data[,3] != 0)

#make a dataframe with logFC, and p-values 

deg2 <- data.frame(logFC = data.fit.eb$coefficients[,3], pval = data.fit.eb$p.value[,3]) 
deg2$ID <- rownames(deg2)

deg2 <- subset(deg2, rownames(deg2) %in% intersect(rownames(deg2), ann$ID))
deg2$ID <- rownames(deg2)
deg2 <- dplyr::left_join(deg2, ann, by = "ID")
#set merged new name as rownames for gene entries

rownames(deg2) <- make.unique(deg2$gene_symbol)
deg2 <- subset(deg2, deg2$ID %in% rownames(sig))

which(deg2$logFC > 2)
deg2[c(5,7,39,73,74,251,323),]

```


